name: CI Docker

on:

  push:
    branches:
      - main
      - feat/teste
    paths:
      - 'docker-compose.yml'
      - 'Dockerfile'
      - '.github/workflows/docker.yml'

  pull_request:
    branches:
      - main
    paths:
      - 'docker-compose.yml'
      - 'Dockerfile'

jobs:

  validar-docker:
    name: Validar Docker
    runs-on: ubuntu-latest

    steps:
      - name: Obtener código
        uses: actions/checkout@v4

      - name: Validar Docker Compose
        run: docker compose config

      - name: Construir imágenes Docker
        run: docker compose build